PicoSchool/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from django.conf.urls.static import static
from PicoSchool import settings

admin.site.site_header = "مدیریت PicoSchool"

urlpatterns = [
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('manager/', include('manager.urls')),
    path('parent/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('poll/', include('poll.urls')),
    path('quiz/', include('quiz.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('pwa.urls')),
    path('pico-school/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = (
    path('', views.index, name='index'),
    path('pages/events/', views.events, name='events'),
    path('pages/notices/', views.notice_box, name='notices'),
    # Student Section
    path('student/<int:pk>/detail/', views.student_detail, name="student_detail"),
    # Parent Section
    path('parent/<int:pk>/detail/', views.parent_detail, name="parent_detail"),
    # Parent Section
    path('teacher/<int:pk>/detail/', views.teacher_detail, name="teacher_detail"),
    # Class Section
    path('class/list/', views.class_list, name="class_list"),
    path('class/<int:pk>/detail/', views.class_detail, name="class_detail"),
    # Attendance Section
    path('attendance/<int:pk>/<date>/detail/', views.attendance_detail, name="attendance_detail"),
    # Home Work Section
    path('home-work/list/', views.home_work_list, name="home_work_list"),
    path('home-work/<int:pk>/detail/', views.home_work_detail, name="home_work_detail"),
    # Employment Form Section
    path('employment-form/list/', views.employment_form_list, name="employment_form_list"),
    path('employment-form/<int:pk>/detail/', views.employment_form_detail, name="employment_form_detail"),
    # News
    path('news/list/', views.news_list, name="news_list"),
)

poll/urls.py
from django.urls import path
from poll import views

app_name = 'poll'

urlpatterns = (
    path('list/', views.poll_list, name='poll_list'),
    path('options/<int:pk>/list/', views.poll_options_list, name='poll_options_list'),
    path('create/', views.PollCreate.as_view(), name='poll_create'),
    path('update/<int:pk>/', views.PollUpdate.as_view(), name='poll_update'),
    path('vote/<int:pk>/', views.poll_vote, name='poll_vote'),
    path('result/<int:pk>/', views.poll_result, name='poll_result'),
)

poll/models.py
from django.db import models
from django.db.models import Count
from django.utils import timezone
from account.models import User


class Poll(models.Model):
    """
    Model for Main Poll
    """

    # Fields
    USER = (
        ('all', 'همه'),
        ('teacher', 'دبیران'),
        ('parent', 'والدین'),
        ('student', 'دانش آموزان'),
    )
    question = models.CharField(
        max_length=30,
        verbose_name='عنوان سوال',
    )
    active = models.BooleanField(
        default=False,
        verbose_name='فعال / غیرفعال',
    )
    for_user = models.CharField(
        max_length=15,
        choices=USER,
        default='all',
        verbose_name='برای کاربران',
    )
    users = models.ManyToManyField(
        User,
        related_name='poll_user',
        blank=True,
        verbose_name='کاربران',
    )
    create = models.DateTimeField(
        default=timezone.now,
        verbose_name='زمان ساخت',
    )

    # Metadata
    class Meta:
        verbose_name = 'نظرسنجی'
        verbose_name_plural = '1. نظرسنجی ها'
        ordering = ('-create',)

    # Methods
    def __str__(self):
        return self.question

    @property
    def all_count(self):
        polls = Poll.objects.all().count()
        return polls


class PollOptions(models.Model):
    """
    Model for Main poll options
    """

    # Fields
    poll = models.ForeignKey(
        Poll,
        on_delete=models.CASCADE,
        related_name='poll_option',
        verbose_name='برای نظرسنجی',
    )
    option = models.CharField(
        max_length=30,
        verbose_name='گزینه',
    )
    option_count = models.IntegerField(
        default=0,
        verbose_name='شمارش گزینه',
    )

    # Metadata
    class Meta:
        verbose_name = 'گزینه'
        verbose_name_plural = '2. گزینه ها'

    # Methods
    def __str__(self):
        return self.option

poll/forms.py
from django import forms

from .models import Poll, PollOptions


class CreatePollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ('question', 'active', 'for_user',)
        widgets = {
            'question': forms.TextInput(
                attrs={'placeholder': 'عنوان نظرسنجی را وارد کنید'}),
        }

poll/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import (
    Http404,
    JsonResponse,
)
from django.shortcuts import (
    render,
    get_object_or_404,
)
from django.urls import reverse_lazy
from django.views import generic
from poll.forms import CreatePollForm
from poll.models import (
    Poll,
    PollOptions,
)


@login_required()
def poll_list(request):
    context = {
        'page_title': 'لیست نظرسنجی ها',
    }
    if request.user.is_superuser or request.user.is_manager:
        context['polls'] = Poll.objects.all()
    elif request.user.is_student:
        context['polls'] = Poll.objects.filter(Q(for_user='student') | Q(for_user='all'))
    elif request.user.is_parent:
        context['polls'] = Poll.objects.filter(Q(for_user='parent') | Q(for_user='all'))
    elif request.user.is_teacher:
        context['polls'] = Poll.objects.filter(Q(for_user='teacher') | Q(for_user='all'))
    return render(request, "poll/poll_list.html", context)


def poll_options_list(request, pk):
    """
    List of Main poll options
    """
    if request.method == "POST" and request.is_ajax:
        poll = get_object_or_404(Poll, pk=pk)
        input_value = {
            'poll': request.POST['poll'],
            'option': request.POST['option'],
        }
        poll.users.clear()
        PollOptions(poll=Poll.objects.get(pk=input_value['poll']), option=input_value['option']).save()
    context = {
        'page_title': 'لیست گزینه ها',
        'options': PollOptions.objects.filter(poll__pk=pk)
    }
    return render(request, "poll/poll_list.html", context)


class PollCreate(LoginRequiredMixin, generic.CreateView):
    form_class = CreatePollForm
    template_name = "poll/poll_create.html"
    success_url = reverse_lazy('poll:poll_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'ساخت نظرسنجی'
        return context


class PollUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Poll
    template_name = "poll/poll_create.html"
    form_class = CreatePollForm
    success_url = reverse_lazy('poll:poll_list')
    context_object_name = "quiz"

    def form_valid(self, form):
        self.obj = form.save(commit=False)
        self.obj.users.clear()
        for option in self.obj.poll_option.all():
            option.option_count = 0
            option.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'ویرایش نظرسنجی'
        return context


@login_required()
def poll_vote(request, pk):
    """
    Vote to main poll options
    """
    poll = get_object_or_404(Poll, pk=pk)
    if request.method == "POST" and request.is_ajax:
        option_id = request.POST['option']
        poll.users.add(request.user)
        option = get_object_or_404(PollOptions, pk=option_id)
        option.option_count += 1
        option.save()
        return JsonResponse({'pk': pk})
    context = {
        'page_title': 'رای به نظرسنجی',
        'poll': poll,
    }
    if poll.active and request.user.pk not in poll.users.values_list('pk', flat=True):
        return render(request, "poll/poll_vote.html", context)
    else:
        raise Http404()


@login_required()
def poll_result(request, pk):
    context = {
        'page_title': 'نتایج نظرسنجی',
        'poll': get_object_or_404(Poll, pk=pk)
    }
    return render(request, "poll/poll_result.html", context)

poll/templates/poll/poll_create.html
{% extends 'base.html' %}

{% block main %}
<div class="m-2">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        {% if request.resolver_match.url_name == "poll_create" %}
        <h3>اضافه کردن نظرسنجی جدید</h3>
        {% elif request.resolver_match.url_name == "poll_update" %}
        <h3>ویرایش نظرسنجی</h3>
        {% endif %}
    </div>
    <!-- Breadcubs Area End Here -->
    <input type="hidden" class="d-none" value="{{ request.resolver_match.url_name }}" id="url_name">
    <!-- Add New Teacher Area Start Here -->
    <div class="card height-auto">
        <div class="card-body">
            <form class="new-added-form" method="post" autocomplete="off">{% csrf_token %}
                <div class="row">
                    <div class="col-lg-8 col-12 form-group">
                        <label> عنوان سوال نظرسنجی <span>*</span></label>
                        {{ form.question }}
                        {% for error in form.question.errors %}
                        <p class="text-danger m-2">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="col-lg-2 col-12 form-group">
                        <label> نمایش به : <span>*</span></label>
                        {{ form.for_user }}
                        {% for error in form.for_user.errors %}
                        <p class="text-danger m-2">{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% if request.resolver_match.url_name == "poll_update" %}
                    <div class="col-lg-2 col-12 form-group">
                        <label> فعال / غیرفعال <span>*</span></label>
                        <label class="switch">
                            {{ form.active }}
                            <span class="slider round"></span>
                        </label>
                        {% for error in form.active.errors %}
                        <p class="text-danger m-2">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="col-md-12">
                        <hr>
                    </div>
                    <div class="col-md-12">
                        <a href="{% url 'poll:poll_options_list' quiz.pk %}" class="btn btn-info w-100">لیست گزینه های نظرسنجی</a>
                    </div>
                    <div class="col-md-12">
                        <hr>
                    </div>
                    {% endif %}
                    <div class="col-12 form-group mg-t-8">
                        <button type="submit" class="btn-fill-lg submit-form-btn">ذخیره</button>
                        <a href="{% url 'poll:poll_list' %}" class="btn-fill-lg reset-form-btn">برگشت</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

poll/templates/poll/poll_list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
{% if request.resolver_match.url_name == "poll_list" %}
<div class="mt-5 m-3">
    <div class="breadcrumbs-area">
        <h3>لیست نظرسنجی ها</h3>
        {% if request.user.is_superuser or request.user.is_manager %}
        <a href="{% url 'poll:poll_create' %}" class="btn">ساخت نظرسنجی</a>
        {% endif %}
    </div>
    <div class="card height-auto">
        <div class="card-body">
            <div class="single-info-details">
                <div class="item-content">
                    <div class="content-inline item-content">
                        <div class="table-box-wrap">
                            <div class="attendance-table table-responsive student-table-box">
                                <table class="table display data-table text-nowrap">
                                    <thead>
                                    <tr>
                                        <th>عنوان</th>
                                        <th>وضعیت</th>
                                        <th></th>
                                        {% if request.user.is_superuser or request.user.is_manager %}
                                        <th></th>
                                        {% endif %}
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for poll in polls %}
                                    <tr class="filter">
                                        <td>
                                            <a href="{% if poll.active and request.user not in poll.users.all %}{% url 'poll:poll_vote' poll.pk %}{% else %}{% url 'poll:poll_result' poll.pk %}{% endif %}"
                                               class="text-secondary"><b>{{ poll.question }}</b></a>
                                        </td>
                                        <td>{% if poll.active == True %}<h2 class="badge badge-success">در جریان</h2>
                                            {% else %}
                                            <h2 class="badge badge-danger">بسته شده</h2>
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if poll.active and request.user not in poll.users.all %}
                                            <a href="{% url 'poll:poll_vote' poll.pk %}" class="btn vote-btn">رای
                                                دادن</a>
                                            {% endif %}
                                            <a href="{% url 'poll:poll_result' poll.pk %}"
                                               class="btn result-btn">نتایج</a>
                                        </td>
                                        {% if request.user.is_superuser or request.user.is_manager %}
                                        <td>
                                            <a href="{% url 'poll:poll_update' poll.pk %}" class="btn btn-warning">ویرایش</a>
                                        </td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% elif request.resolver_match.url_name == "poll_options_list" %}
<div class="mt-5 m-3">
    <div class="breadcrumbs-area">
        <h3>لیست گزینه های نظرسنجی</h3>
    </div>
    <div class="card height-auto">
        <div class="card-body">
            <div class="single-info-details">
                <div class="item-content">
                    <div class="row">
                        <div class="col-md-12">
                            {% for option in options %}
                            <div class="bg-outline-secondary w-100 my-3 p-2 text-light">
                                <h3>{{ option.pk }}- {{ option }}</h3>
                            </div>
                            {% empty %}
                            <div class="text-center">
                                <h3 class="text-danger"><b>گزینه ای پیدا نشد</b></h3>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="col-lg-12 col-12 text-center">
                            <button type="button" class="btn btn-primary" data-toggle="collapse"
                                    data-target=".opt-collapse">
                                <i class="fas fa-plus-circle"></i>
                                افزودن گزینه
                            </button>
                        </div>
                        <div class="col-md-12">
                            <div class="bg-light collapse opt-collapse">
                                <div class="card-body my-4">
                                    <div class="row">
                                        {% csrf_token %}
                                        <div class="col-md-6 m-auto">
                                            <input type="hidden" id="poll_id"
                                                   value="{{ request.resolver_match.kwargs.pk }}">
                                            <input type="text" class="form-control"
                                                   placeholder="عنوان گزینه را وارد کنید" id="option_text">
                                        </div>
                                        <div class="col-md-12 text-center mt-3">
                                            <button class="btn btn-success" id="submit-btn">ساخت گزینه</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <a href="{% url 'poll:poll_list' %}" class="btn btn-secondary">برگشت</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% block js_files %}<script src='{% static "poll/poll.js" %}'></script>{% endblock %}
{% endif %}
{% endblock %}

poll/templates/poll/poll_result.html
{% extends 'base.html' %}

{% block main %}
<div class="m-2">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>نتایج نظرسنجی</h3>
    </div>
    <!-- Breadcubs Area End Here -->
    <!-- Add New Teacher Area Start Here -->
    <div class="card height-auto">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    {{ poll.question }}
                    <hr>
                </div>
                {% for option in poll.poll_option.all %}
                <div class="col-md-4">
                    <h4>{{ option }} ----- <b>{{ option.option_count }} رای </b></h4>
                </div>
                <div class="col-md-8">
                    <div class="progress mt-2" style="height: 20px;">
                        <div class="progress-bar bg-info" role="progressbar"
                             style="width: {{ option.option_count }}cm" aria-valuenow="{{ option.option_count }}"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
                {% endfor %}
                <a href="{% url 'poll:poll_list' %}" class="btn btn-secondary">برگشت</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

poll/templates/poll/poll_vote.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<div class="m-2">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>نظرسنجی <b>"{{ poll }}"</b>  </h3>
    </div>
    <!-- Breadcubs Area End Here -->
    <!-- Add New Teacher Area Start Here -->
    <div class="card height-auto">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="text-center">{{ poll.question }}</h3>
                </div>
                    {% csrf_token %}
                    <input type="hidden" id="poll_pk" value="{{ poll.pk }}">
                    {% for option in poll.poll_option.all %}
                    <div class="col-md-12">
                        <label class="rdButton">
                            <input type="radio" name="poll" value="{{ option.pk }}">
                            <span class="checkmark"></span>
                            <p>{{ option }}</p>
                        </label>
                    </div>
                    {% endfor %}
                    <div class="col-md-12">
                        <hr>
                    </div>
                    <div class="col-12">
                        <button type="button" class="btn btn-success" id="vote-btn">
                            ثبت
                        </button>
                        <a href="{% url 'poll:poll_list' %}" class="btn btn-secondary">برگشت</a>
                    </div>
            </div>
        </div>
    </div>
</div>
{% block js_files %}<script src='{% static "poll/poll.js" %}'></script>{% endblock %}
{% endblock %}