PicoSchool/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from django.conf.urls.static import static
from PicoSchool import settings

admin.site.site_header = "مدیریت PicoSchool"

urlpatterns = [
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('manager/', include('manager.urls')),
    path('parent/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('poll/', include('poll.urls')),
    path('quiz/', include('quiz.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('pwa.urls')),
    path('pico-school/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = (
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/password-change/', views.ChangePasswordView.as_view(), name='change_password'),
    path('user/password-done/', views.password_change_done, name="user_password_done"),
)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = (
    path('', views.index, name='index'),
    path('pages/events/', views.events, name='events'),
    path('pages/notices/', views.notice_box, name='notices'),
    # Student Section
    path('student/<int:pk>/detail/', views.student_detail, name="student_detail"),
    # Parent Section
    path('parent/<int:pk>/detail/', views.parent_detail, name="parent_detail"),
    # Parent Section
    path('teacher/<int:pk>/detail/', views.teacher_detail, name="teacher_detail"),
    # Class Section
    path('class/list/', views.class_list, name="class_list"),
    path('class/<int:pk>/detail/', views.class_detail, name="class_detail"),
    # Attendance Section
    path('attendance/<int:pk>/<date>/detail/', views.attendance_detail, name="attendance_detail"),
    # Home Work Section
    path('home-work/list/', views.home_work_list, name="home_work_list"),
    path('home-work/<int:pk>/detail/', views.home_work_detail, name="home_work_detail"),
    # Employment Form Section
    path('employment-form/list/', views.employment_form_list, name="employment_form_list"),
    path('employment-form/<int:pk>/detail/', views.employment_form_detail, name="employment_form_detail"),
    # News
    path('news/list/', views.news_list, name="news_list"),
)

quiz/urls.py
from django.urls import path

from quiz import views

app_name = "quiz"

urlpatterns = (
    path('list/', views.quiz_list, name='quiz_list'),
    path('<int:pk>/detail/', views.quiz_detail, name='quiz_detail'),
    path('detail/<int:pk>/<uuid>/', views.quiz_start, name='quiz_start'),
    path('create/', views.CreateQuiz.as_view(), name='quiz_create'),
    path('<int:pk>/update/', views.UpdateQuiz.as_view(), name='quiz_update'),
    # Questions Section
    path('questions/<int:pk>/list/', views.quiz_questions_list, name='quiz_questions_list'),
    path('questions/<int:pk>/update/', views.UpdateQuestion.as_view(), name='question_update'),
    path('questions-update/', views.update_question, name='update_question'),
    path('answers-update/', views.update_answers, name='update_answers'),
    path('create-answers/', views.create_answers, name='create_answers'),
    path('get-question/', views.get_questions, name='get_questions'),
    path('answers/', views.answers_data, name='answers_data'),
    # Result Section
    path('result/list/', views.result_list, name='result_list'),
    path('result/<pk>/<stu_pk>/detail/', views.result_detail, name='result_detail'),
    path('create-result/', views.create_result, name='create_result'),
    path('create-result-2/', views.create_result_2, name='create_result_2'),
    path('result-data/<int:pk>/', views.result_data, name='result_data'),
)

student/urls.py
from django.urls import path
from student import views

app_name = 'student'

urlpatterns = [
    path('', views.student_view, name='student_panel'),
    # Employment Form Section
    path('create-emp-form/', views.create_emp_form, name='create_emp_form'),
]

student/models.py
from django.db import models

student/views.py
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_POST
from account.models import User
from main.decorators import allow_user
from manager.models import (
    NoticeBox,
    Major,
    EmploymentForm,
    Assign,
)
from quiz.models import QuizResult


@allow_user(["is_superuser", "is_manager", "is_student"])
def student_view(request):
    def all_status_func():
        all_status = Assign.objects.filter(student=request.user).aggregate(count=Count('id'))
        count_all = 0
        if all_status["count"] is not None:
            count_all = int(all_status["count"])
        return count_all

    def present_percent():
        present = Assign.objects.filter(student=request.user, attendance_status='حاضر').aggregate(count=Count('id'))
        count_present = 0
        if present["count"] is not None:
            count_present = int(present["count"])
        try:
            result = round((count_present / all_status_func()) * 100, 0)
        except ZeroDivisionError:
            result = 0
        return result

    def absent_percent():
        absent = Assign.objects.filter(student=request.user, attendance_status='غایب').aggregate(count=Count('id'))
        count_present = 0
        if absent["count"] is not None:
            count_present = int(absent["count"])
        try:
            result = round((count_present / all_status_func()) * 100, 0)
        except ZeroDivisionError:
            result = 0
        return result

    def plate_percent():
        plate = Assign.objects.filter(student=request.user, attendance_status='حاضر (با تاخیر)').aggregate(
            count=Count('id'))
        count_present = 0
        if plate["count"] is not None:
            count_present = int(plate["count"])
        try:
            result = round((count_present / all_status_func()) * 100, 0)
        except ZeroDivisionError:
            result = 0
        return result

    context = {
        "notices": NoticeBox.objects.all().order_by('-publish')[:10],
        "page_title": "پنل دانش آموزان",
        'majors': Major.objects.all(),
        'present': present_percent(),
        'absent': absent_percent(),
        'plate': plate_percent(),
        'results': QuizResult.objects.filter(user=request.user),
    }
    return render(request, "student/student_panel.html", context)


@require_POST
@allow_user(['is_superuser', 'is_manager', 'is_student'])
def create_emp_form(request):  # add employment form status
    input_value = {
        'stu_id': request.POST.get('stu_id'),
        'organ': request.POST.get('organ'),
    }

    print(input_value)
    emp_form = EmploymentForm(student=User.objects.get(id=input_value['stu_id']),
                              organ=input_value['organ'])
    emp_form.save()
    return HttpResponse(input_value)

student/templates/student/student_panel.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<!-- Breadcubs Area Start Here -->
<div class="breadcrumbs-area">
    <h3>داشبورد دانش آموزان</h3>
    <ul>
        <li>{{ request.user.get_full_name }}</li>
    </ul>
</div>
<!-- Breadcubs Area End Here -->
<div class="row">
    <!-- Student Info Area Start Here -->
    <div class="col-4-xxxl col-12">
        <div class="card dashboard-card-ten">
            <div class="card-body">
                <div class="heading-layout1">
                    <div class="item-title">
                        <h3>درباره من</h3>
                    </div>
                    <div class="dropdown">
                        <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                           aria-expanded="false">...</a>

                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{% url 'main:student_detail' request.user.pk %}"><i
                                    class="fas fa-cogs text-dark-pastel-green"></i>نمایش اطلاعات</a>
                            <a class="dropdown-item" href=""><i
                                    class="fas fa-redo-alt text-orange-peel"></i>تازه کردن</a>
                        </div>
                    </div>
                </div>
                <div class="student-info">
                    <div class="media media-none--xs">
                        <div class="item-img">
                            {% if request.user.profile_img %}
                            <img src="{{ request.user.profile_img.url }}" class="media-img-auto"
                                 alt="{{ request.user.national_code }}">
                            {% else %}
                            <img src="{% static 'img/user_image.png' %}" class="student_img media-img-auto"
                                 width="110px"
                                 alt="{{ request.user.national_code }}">
                            {% endif %}
                        </div>
                        <div class="media-body">
                            <a href="{% url 'main:student_detail' request.user.pk %}">
                                <h3 class="item-title">{{ request.user.get_full_name }}</h3>
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive info-table">
                        <table class="table text-nowrap">
                            <tbody>
                            <tr>
                                <td>نام و نام خانوادگی:</td>
                                <td class="font-medium text-dark-medium">{{ request.user.get_full_name }}</td>
                            </tr>
                            <tr>
                                <td>نام پدر:</td>
                                <td class="font-medium text-dark-medium">{{ request.user.father_name }}</td>
                            </tr>
                            <tr>
                                <td>تاریخ تولد:</td>
                                <td class="font-medium text-dark-medium">{{ request.user.date_of_birth }}</td>
                            </tr>
                            <tr>
                                <td>تلفن:</td>
                                {% if request.user.phone %}
                                <td class="font-medium text-dark-medium">{{ request.user.phone }}</td>
                                {% else %}
                                <td class="font-medium text-dark-medium">ندارد</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>تلفن منزل:</td>
                                <td class="font-medium text-dark-medium">{{ request.user.home_phone }}</td>
                            </tr>
                            <tr>
                                <td><a href="{% url 'main:student_detail' request.user.pk %}" class="btn btn-secondary">اطلاعات
                                    بیشتر</a></td>
                                <td><a href="{% url 'account:change_password' %}" class="btn btn-warning">تغییر
                                    گذرواژه</a></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Student Info Area End Here -->
    <div class="col-8-xxxl col-12">
        <div class="row">
            <!-- Summery Area Start Here -->
            <div class="col-lg-4">
                <div class="dashboard-summery-one theme_color">
                    <div class="row">
                        <div class="col-6">
                            <div class="item-icon">
                                <i class="flaticon-shopping-list"></i>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item-content">
                                <div class="item-title">اطلاعیه</div>
                                <div class="item-number"><span class="counter" data-num="12">
                                    {% if count_notice_header %}{{ count_notice_header.count }}{% else %}0{% endif %}
                                </span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="dashboard-summery-one theme_color">
                    <div class="row">
                        <div class="col-6">
                            <div class="item-icon">
                                <i class="flaticon-calendar"></i>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item-content">
                                <div class="item-title">رویداد</div>
                                <div class="item-number"><span class="counter">
                                    {% if event_count %}{{ event_count.count }}{% else %}0{% endif %}
                                </span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="dashboard-summery-one theme_color">
                    <div class="row">
                        <div class="col-6">
                            <div class="item-icon">
                                <i class="flaticon-percentage-discount"></i>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item-content">
                                <div class="item-title">حضور</div>
                                <div class="item-number"><span class="counter">{{ present }}</span><span>%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Summery Area End Here -->
            <!-- Exam Result Area Start Here -->
            <div class="col-lg-12">
                <div class="card dashboard-card-eleven">
                    <div class="card-body">
                        <div class="heading-layout1">
                            <div class="item-title">
                                <a href="{% url 'quiz:result_list' %}"><h3>نتایج آزمون</h3></a>
                            </div>
                        </div>
                        <div class="table-box-wrap">
                            <div class="table-responsive result-table-box">
                                <table class="table display data-table text-nowrap">
                                    <thead>
                                    <tr>
                                        <th>
                                        </th>
                                        <th>نام آزمون</th>
                                        <th>موضوع</th>
                                        <th>کلاس</th>
                                        <th>کتاب</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for result in results %}
                                    <tr>
                                        <td>
                                            {{ result.pk }}
                                        </td>
                                        <td>{{ result.quiz }}</td>
                                        <td>{{ result.quiz.topic }}</td>
                                        <td>{{ result.quiz.quiz_class }}</td>
                                        <td>{{ result.quiz.quiz_book }}</td>
                                        <td>
                                            <div class="dropdown">
                                                <a href="#" class="dropdown-toggle"
                                                   data-toggle="dropdown" aria-expanded="false">
                                                                        <span
                                                                                class="flaticon-more-button-of-three-dots"></span>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item"
                                                       href="{% url 'quiz:result_detail' result.pk request.user.pk %}"><i
                                                            class="fas fa-cogs text-dark-pastel-green"></i>جزئیات</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Exam Result Area End Here -->
        </div>
    </div>
    <div class="col-4-xxxl col-xl-6 col-12">
        {% include 'student_status.html' %}
    </div>
    <div class="col-4-xxxl col-xl-6 col-12">
        {% include 'event_calendar.html' %}
    </div>
    <div class="col-4-xxxl col-12">
        {% include 'notice_boxes.html' %}
    </div>
</div>
{% block js_files %}
<!-- Chart Js -->
<script src="{% static 'js/chart.min.js' %}"></script>
<script src="{% static 'js/student_chart.js' %}"></script>
{% endblock %}
{% endblock %}