PicoSchool/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from django.conf.urls.static import static
from PicoSchool import settings

admin.site.site_header = "مدیریت PicoSchool"

urlpatterns = [
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('manager/', include('manager.urls')),
    path('parent/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('poll/', include('poll.urls')),
    path('quiz/', include('quiz.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('pwa.urls')),
    path('pico-school/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = (
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/password-change/', views.ChangePasswordView.as_view(), name='change_password'),
    path('user/password-done/', views.password_change_done, name="user_password_done"),
)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = (
    path('', views.index, name='index'),
    path('pages/events/', views.events, name='events'),
    path('pages/notices/', views.notice_box, name='notices'),
    # Student Section
    path('student/<int:pk>/detail/', views.student_detail, name="student_detail"),
    # Parent Section
    path('parent/<int:pk>/detail/', views.parent_detail, name="parent_detail"),
    # Parent Section
    path('teacher/<int:pk>/detail/', views.teacher_detail, name="teacher_detail"),
    # Class Section
    path('class/list/', views.class_list, name="class_list"),
    path('class/<int:pk>/detail/', views.class_detail, name="class_detail"),
    # Attendance Section
    path('attendance/<int:pk>/<date>/detail/', views.attendance_detail, name="attendance_detail"),
    # Home Work Section
    path('home-work/list/', views.home_work_list, name="home_work_list"),
    path('home-work/<int:pk>/detail/', views.home_work_detail, name="home_work_detail"),
    # Employment Form Section
    path('employment-form/list/', views.employment_form_list, name="employment_form_list"),
    path('employment-form/<int:pk>/detail/', views.employment_form_detail, name="employment_form_detail"),
    # News
    path('news/list/', views.news_list, name="news_list"),
)

manager/urls.py
from django.urls import path
from account.views import password_change_done
from manager import views

app_name = 'manager'

urlpatterns = (
    path('', views.manager_panel, name='manager_panel'),
    # Calendar section
    path('calendar/', views.calendar, name='calendar'),
    path('add-event/', views.add_event, name='add_event'),
    path('add-ex-event/', views.add_external_event, name='add_external_event'),
    path('update-event/', views.update_event, name='update_event'),
    path('update-event-desc/', views.update_event_desc, name='update_event_desc'),
    path('delete-event/', views.delete_event, name='delete_event'),
    path('delete-ex-event/', views.delete_ex_event, name='delete_ex_event'),
    # Notice Box section
    path('add-notice/', views.add_notice, name='add_notice'),
    path('edit-notice/', views.edit_notice, name='edit_notice'),
    path('delete-notice/', views.delete_notice, name='delete_notice'),
    # Student section
    path('student/list/', views.student_list, name="student_list"),
    path('student/create/', views.CreateStudent.as_view(), name="student_create"),
    path('student/<int:pk>/change', views.UpdateStudent.as_view(), name="student_update"),
    path('student/<int:pk>/delete', views.DeleteStudent.as_view(), name="student_delete"),
    # Parent section
    path('parent/list/', views.parent_list, name="parent_list"),
    path('parent/create/', views.CreateParent.as_view(), name="parent_create"),
    path('parent/<int:pk>/change', views.UpdateParent.as_view(), name="parent_update"),
    path('parent/<int:pk>/delete', views.DeleteParent.as_view(), name="parent_delete"),
    # Teacher section
    path('teacher/list/', views.teacher_list, name="teacher_list"),
    path('teacher/create/', views.CreateTeacher.as_view(), name="teacher_create"),
    path('teacher/<int:pk>/change', views.UpdateTeacher.as_view(), name="teacher_update"),
    path('teacher/<int:pk>/delete', views.DeleteTeacher.as_view(), name="teacher_delete"),
    # Persons Section
    path('user/<int:pk>/password/', views.password_change, name="user_password"),
    path('password-done/', password_change_done, name="user_password_done"),
    # Attendance Section
    path('change-att-status/', views.change_att_status, name='change_att_status'),
    path('add-att-status/', views.add_att_status, name='add_att_status'),
    path('create-att/', views.create_att, name='create_att'),
    path('change-att-note/', views.change_att_note, name='change_att_note'),
    # Report Card Section
    path('report-card/', views.report_card, name='report_card'),
    # Home Work Section
    path('create-hw/', views.create_hw, name='create_hw'),
    # Employment Form Section
    path('upload-emp-form/', views.upload_emp_form, name='upload_emp_form'),
)

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="fa">
{% load pwa %}
{% progressive_web_app_meta %}
<head>
    {% include 'header_references.html' %}
    <!-- Favicon -->
    <title>{{ page_title }}</title>
    <link rel="icon" type="image/png" href="{% if setting %}{{ setting.favicon.url }}{% else %}{% static 'main/img/pico_school_logo.png' %}{% endif %}">
</head>
<body>
<div id="wrapper" class="wrapper bg-ash">
    {% include 'header.html' %}
    <!-- Page Area Start Here -->
    <div class="dashboard-page-one">
        {% include 'sidebar.html' %}
        <div class="dashboard-content-one">
            {% block main %}{% endblock %}
            {% include "footer.html" %}
        </div>
    </div>
    <!-- Page Area End Here -->
</div>
{% include "footer_references.html" %}
{% block js_files %}{% endblock %}
</body>
</html>

templates/event_calendar.html
{% load static %}
<div class="card dashboard-card-four pd-b-20" id="MEventCalendar">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <a href="{% url 'main:events' %}"><h3>تقویم رویداد</h3></a>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-expanded="false">...</a>

                <div class="dropdown-menu dropdown-menu-right">
                    {% if request.user.is_superuser or request.user.is_manager %}
                    <a class="dropdown-item" href="{% url 'manager:calendar' %}"><i
                            class="fas fa-cogs text-dark-pastel-green"></i>ویرایش</a>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'main:events' %}"><i
                            class="far fa-calendar-alt text-blue"></i>رویداد ها</a>
                    <a class="dropdown-item" href="{{ request.path }}#MEventCalendar"><i
                            class="fas fa-redo-alt text-orange-peel"></i>تازه کردن</a>
                </div>
            </div>
        </div>
        <div class="calender-wrap">
            <div id="calendar"></div>
        </div>
    </div>
</div>
{% block js_files %}
<!-- Calendar Js -->
<script src="{% static 'manager/fullcalendar/main.min.js' %}"></script>
<script src="{% static 'manager/js/moment-with-locales.min.js' %}"></script>
<script src="{% static 'manager/fullcalendar-daygrid/main.min.js' %}"></script>
<script src="{% static 'manager/fullcalendar-timegrid/main.min.js' %}"></script>
<script src="{% static 'manager/fullcalendar-interaction/main.min.js' %}"></script>
<script src="{% static 'manager/fullcalendar-bootstrap/main.min.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
    var calendarEl = document.getElementById("calendar");

    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: ["bootstrap", "interaction", "dayGrid", "timeGrid"],

        eventColor: "#007bff",
        timeZone: "Asia/Tehran",
        locale: "fa",
        selectable: true,
        eventDidMount: function (info) {
            var tooltip = new Tooltip(info.el, {
                title: info.event.extendedProps.description,
                placement: "top",
                trigger: "hover",
                container: "body",
            });
        },
        events: [
            {% for event in events %}
            {
                id: "{{ event.id }}",
                title: "{{ event.title }}",
                start: "{{ event.start }}",
                end: "{{ event.end }}",
                description: "{{ event.description }}",
                backgroundColor: "{{ event.backgroundColor }}",
                borderColor: "{{ event.borderColor }}",
            },
            {% endfor %}
        ],
        eventClick: function (info) {
            if (info.event.extendedProps.description != "None") document.getElementById("eventModalBody").innerHTML = `${info.event.extendedProps.description}`;
            else document.getElementById("eventModalBody").innerHTML = "توضیحی برای این رویداد وجود ندارد!";
            document.getElementById("eventModalHeader").innerHTML = info.event.title;
            $("#exampleModalCenter").modal("show");
        },
    });
    var mediaQuery = window.matchMedia("(max-width: 768px)");
    if (mediaQuery.matches) {
        calendar.setOption("height", 500);
    }
    calendar.render();
});

</script>
{% endblock %}

templates/footer.html
<!-- Footer Area Start Here -->
<footer class="footer-wrap-layout1 noPrint">
    <div class="copyright">کپی رایت و حقوق محفوظ است. طراحی و توسعه توسط
        <a target="_blank" href="https://github.com/AminAliH47">AminAlih47</a>
    </div>
</footer>
<!-- Footer Area End Here -->

templates/footer_references.html
{% load static %}
<!-- jquery-->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- jquery UI-->
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<!-- Plugins js -->
<script src="{% static 'js/plugins.js' %}"></script>
<!-- Popper js -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap js -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Counterup Js -->
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<!-- Waypoints Js -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<!-- Scroll Up Js -->
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<!-- MyScripts -->
<script src='{% static "js/scripts.js" %}'></script>

templates/header.html
{% load static %}
<!-- Header Menu Area Start Here -->
<div class="navbar navbar-expand-md header-menu-one bg-light">
    <div class="nav-bar-header-one">
        <div class="header-logo">
            <a href="{% url 'account:login' %}">
                <img src="{{ setting.school_logo.url }}" alt="{{ setting.school_name }}" width="100px"
                     style="object-fit:scale-down;">
            </a>
        </div>
        <div class="toggle-button sidebar-toggle">
            <button onclick="openNav()" type="button" class="item-link">
                        <span class="btn-icon-wrap">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
            </button>
        </div>
    </div>
    <div class="d-md-none mobile-nav-bar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mobile-navbar"
                aria-expanded="false">
            <i class="far fa-arrow-alt-circle-down"></i>
        </button>
        <button onclick="openNav()" type="button" class="navbar-toggler sidebar-toggle-mobile">
            <i id="NavTogglerMo" class="fas fa-bars"></i>
        </button>
    </div>
    <div class="header-main-menu collapse navbar-collapse" id="mobile-navbar">
        <ul class="navbar-nav">
            <li class="navbar-item header-search-bar">
                <div class="input-group stylish-input-group">
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="navbar-item dropdown header-admin">
                <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-expanded="false">
                    <div class="admin-title">
                        <h5 class="item-title">{{ request.user.get_full_name }}</h5>
                        <span>{% if request.user.is_superuser or request.user.is_manager %}مدیر{% elif request.user.is_parent %}والدین{% elif request.user.is_teacher %}دبیر{% elif request.user.is_student %}دانش آموز{% endif %}</span>
                    </div>
                    <div class="admin-img">
                        {% if request.user.profile_img %}
                        <img src="{{ request.user.profile_img.url }}" alt="{{ request.user.national_code }}">
                        {% else %}
                        <img src="{% static 'img/user_image.png' %}" alt="{{ request.user.national_code }}"
                             width="40px">
                        {% endif %}
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="item-header">
                        <h6 class="item-title">{{ request.user.get_full_name }}</h6>
                    </div>
                    <div class="item-content" style="text-align: right;">
                        <ul class="settings-list">
                            <li><a href="{% if request.user.is_student %}{% url 'main:student_detail' request.user.pk %}{% elif request.user.is_parent %}{% url 'main:parent_detail' request.user.pk %}{% elif request.user.is_teacher %}{% url 'main:teacher_detail' request.user.pk %}{% endif %}"><i class="flaticon-user"></i>پروفایل من</a></li>
                            <li><a href="{% url 'account:login' %}"><i class="flaticon-list"></i>داشبورد</a></li>
                            <li><a href="{% url 'account:change_password' %}"><i class="flaticon-gear-loading"></i>تغییر گذرواژه</a></li>
                            <li><a href="#" data-toggle="modal" data-target="#logout_modal"><i
                                    class="flaticon-turn-off"></i>خروج</a></li>
                        </ul>
                    </div>
                </div>
            </li>
            <li class="navbar-item dropdown header-message">
                <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-expanded="false">
                    <i class="far fa-bell"></i>
                    <div class="item-title d-md-none text-16 mg-l-10">اعلانات</div>
                    <span>{% if count_notice_header %}{{ count_notice_header.count }}{% else %}0{% endif %}</span>
                </a>

                <div class="dropdown-menu dropdown-menu-right text-right">
                    <div class="item-header">
                        <h6 class="item-title">اعلانات</h6>
                    </div>
                    <div class="item-content">
                        {% if notices_header %}
                        {% for notice in notices_header %}
                        <div class="media">
                            <div class="media-body space-sm">
                                <div class="item-title">
                                    <a href="#">
                                        <span class="item-name">{{ notice.writer.get_full_name }}</span>
                                    </a>
                                </div>
                                <h5 style="margin-bottom: 0;margin-top: 12px;">{{ notice.title }}</h5>
                                <p>{{ notice.description|truncatewords_html:7 }}</p>
                            </div>
                        </div>
                        <hr>
                        {% endfor %}
                        <div class="events-btn text-center">
                            <a href="{% url 'main:notices' %}">تمام اعلانات</a>
                        </div>
                        {% else %}
                        <h5 class="text-center">اعلانی برای نمایش وجود ندارد</h5>
                        {% endif %}
                    </div>
                </div>
            </li>
            <li class="navbar-item dropdown header-notification">
                <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-expanded="false">
                    <i class="far fa-calendar-alt"></i>
                    <div class="item-title d-md-none text-16 mg-l-10">رویداد ها</div>
                    <span>{% if event_count %}{{ event_count.count }}{% else %}0{% endif %}</span>
                </a>

                <div class="dropdown-menu dropdown-menu-right text-right">
                    <div class="item-header">
                        <h6 class="item-title">رویداد ها</h6>
                    </div>
                    <div class="item-content">
                        {% if events %}
                        {% for event in dropdown_events %}
                        <div class="media">
                            <div class="item-icon bg-orange">
                                <i class="fas fa-calendar-alt"></i>
                            </div>
                            <div class="media-body space-sm">
                                <a href="{% url 'main:events' %}">
                                    <div class="post-title"><b>{{ event.title }}</b></div>
                                </a>
                                <span>{{ event.jstart }}</span>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="events-btn text-center">
                            <a href="{% url 'main:events' %}">تمام رویداد ها</a>
                        </div>
                        {% else %}
                        <h5 class="text-red">رویدادی برای نمایش وجود ندارد</h5>
                        {% endif %}
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="modal fade" id="logout_modal" tabindex="-1" role="dialog" aria-labelledby="logout_modal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header"><h5 class="modal-title"
                                          id="logout_modalLabel">خروج از اکانت</h5>
                <button type="button" class="close ml-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body"><p>آیا میخواهید از اکانت خود خارج شوید؟</p></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mx-1" data-dismiss="modal"
                        aria-label="Close">لغو
                </button>
                <a href="{% url 'account:logout' %}" class="btn btn-danger">خروج</a>
            </div>
        </div>
    </div>
</div>
<!-- Header Menu Area End Here -->

templates/header_references.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Normalize CSS -->
<!--<link rel="stylesheet" href="{% static 'css/normalize.css' %}">-->
<!-- Bootstrap4 CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!-- Fontawesome CSS -->
<link rel="stylesheet" href="{% static 'css/all.min.css' %}">
<!-- Flaticon CSS -->
<link rel="stylesheet" href="{% static 'fonts/flaticon.css' %}">
<!-- Animate CSS -->
<!--<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">-->
<!-- Calendar CSS -->
<link rel="stylesheet" href="{% static 'manager/fullcalendar/main.min.css' %}">
<link rel="stylesheet" href="{% static 'manager/fullcalendar-daygrid/main.min.css' %}">
<link rel="stylesheet" href="{% static 'manager/fullcalendar-timegrid/main.min.css' %}">
<link rel="stylesheet" href="{% static 'manager/fullcalendar-bootstrap/main.min.css' %}">
<!-- Style CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- Responsive CSS -->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<!-- CKeditor CSS -->
{% if request.resolver_match.url_name == "quiz_create" or request.resolver_match.url_name == "quiz_update" %}
<link rel="stylesheet" href="{% static 'css/dialog.css' %}">
<link rel="stylesheet" href="{% static 'css/editor.css' %}">
{% endif %}
<!-- Theme CSS -->
{% if setting %}
    {% if setting.site_menu_theme == 'waterfall' %}
    <link rel="stylesheet" href="{% static 'css/waterfall_menu.css' %}">
    {% elif setting.site_menu_theme == 'four_rooms' %}
    <link rel="stylesheet" href="{% static 'css/four_rooms_menu.css' %}">
    {% else %}
    <link rel="stylesheet" href="{% static 'css/waterfall_menu.css' %}">
    {% endif %}
    {% if setting.site_color == "green" %}
        <link rel="stylesheet" href="{% static 'css/green_theme.css' %}">
    {% elif setting.site_color == "orange" %}
        <link rel="stylesheet" href="{% static 'css/orange_theme.css' %}">
    {% elif setting.site_color == "yellow" %}
        <link rel="stylesheet" href="{% static 'css/yellow_theme.css' %}">
    {% endif %}
{% else %}
    <link rel="stylesheet" href="{% static 'css/green_theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/waterfall_menu.css' %}">
{% endif %}

templates/notice_boxes.html
<div class="card dashboard-card-six">
    <div class="card-body">
        <div class="heading-layout1 mg-b-17">
            <div class="item-title">
                <a href="{% url 'main:notices' %}">
                    <h3>تابلو اعلانات</h3>
                </a>
            </div>
        </div>
        <div class="notice-box-wrap">
            {% if notices %}
            {% for notice in notices %}
            <div id="ENB{{ notice.id }}">
                {% if request.user.is_superuser or request.user.is_manager %}
                <button type="button" name="{{ notice.id }}" class="delete_notice"><i
                        class="fas fa-trash text-red notice_trash_icon"></i></button>
                {% if request.resolver_match.url_name == "notices" %}
                <button type="button" name="{{ notice.id }}" class="edit_notice"><i
                        class="fas fa-edit text-red notice_edit_icon"></i></button>
                {% endif %}
                {% endif %}
                <div class="notice-list theme_color" id="{{ notice.id }}">
                    <div class="post-date">{{ notice.jpublish }}</div>
                    <h6 class="notice-title"><a href="{% url 'main:notices' %}#{{ notice.id }}">
                        {{ notice.title }}</a></h6>
                    {% if request.resolver_match.url_name == "notices" %}
                    <p class="notice-title">{{ notice.description }}</p>
                    {% endif %}
                    <div class="entry-meta"><span>{{ notice.publish|timesince }} پیش</span> /
                        <span id="notice_writer2"><span>{{notice.writer.id}}</span> {{ notice.writer.get_full_name }}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h5 class="text-danger font-weight-bold text-center">اعلانی برای نمایش وجود ندارد</h5>
            {% endif %}
        </div>
    </div>
</div>
<div class="modal fade" id="edit_notice_modal" tabindex="-1" role="dialog" aria-labelledby="notices_modal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header"><h5 class="modal-title"
                                          id="logout_modalLabel">افزودن اعلان جدید</h5>
                <button type="button" class="close ml-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="add_notice">
                    {% if request.user.is_superuser or request.user.is_manager %}
                    <div class="dropdown">
                        <form method="post">
                            {% csrf_token %}
                            <button class="btn btn-secondary dropdown-toggle Notice_writer" type="button"
                                    data-toggle="dropdown" aria-haspopup="true" name="" aria-expanded="false">
                                نویسنده
                            </button>
                            <div id="UsersDropdown" class="dropdown-menu text-right p-2"
                                 aria-labelledby="dropdownMenuButton">
                                <input type="text" placeholder="جستجو نام..." class="searchInput"
                                       onkeyup="search_users()">
                                {% for user in users %}
                                <button class="dropdown-item noticeWr" type="button" name="user_name"
                                        id="id{{ user.id }}">
                                    {{ user.id }} {{ user.get_full_name }}
                                </button>
                                {% endfor %}
                            </div>
                        </form>
                    </div>
                    {% endif %}
                    <p>عنوان اعلان<span>*</span></p>
                    <input type="text" id="Enotice_title2" placeholder="عنوان اعلان را بنویسید">
                    <p>توضیحات اعلان<span>*</span></p>
                    <textarea name="notice_description" id="Enotice_description2" placeholder="توضیحات اعلان را بنویسید"
                              cols="30" rows="10"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mx-1" data-dismiss="modal"
                        aria-label="Close">لغو
                </button>
                <button type="button" onclick="edit_notice()" class="btn submit-notice">ارسال</button>
            </div>
        </div>
    </div>
</div>

templates/student_status.html
<div class="card dashboard-card-three">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>حضور</h3>
            </div>

        </div>
        <div class="doughnut-chart-wrap">
            <canvas id="studentChart"></canvas>
            <input type="hidden" class="d-none" value="{{ present }}" id="stuPresent">
            <input type="hidden" class="d-none" value="{{ absent }}" id="stuAbsent">
            <input type="hidden" class="d-none" value="{{ plate }}" id="stuPlate">
        </div>
        <div class="student-report">
            <div class="student-count pseudo-bg-red">
                <h4 class="item-title">غایب</h4>
                <div class="item-number">{{ absent }}%</div>
            </div>
            <div class="student-count pseudo-bg-green">
                <h4 class="item-title">حاضر</h4>
                <div class="item-number">{{ present }}%</div>
            </div>
        </div>
    </div>
</div>