PicoSchool/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from django.conf.urls.static import static
from PicoSchool import settings

admin.site.site_header = "مدیریت PicoSchool"

urlpatterns = [
    path('', include('account.urls')),
    path('', include('main.urls')),
    path('manager/', include('manager.urls')),
    path('parent/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('poll/', include('poll.urls')),
    path('quiz/', include('quiz.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('pwa.urls')),
    path('pico-school/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = (
    path('', views.index, name='index'),
    path('pages/events/', views.events, name='events'),
    path('pages/notices/', views.notice_box, name='notices'),
    # Student Section
    path('student/<int:pk>/detail/', views.student_detail, name="student_detail"),
    # Parent Section
    path('parent/<int:pk>/detail/', views.parent_detail, name="parent_detail"),
    # Parent Section
    path('teacher/<int:pk>/detail/', views.teacher_detail, name="teacher_detail"),
    # Class Section
    path('class/list/', views.class_list, name="class_list"),
    path('class/<int:pk>/detail/', views.class_detail, name="class_detail"),
    # Attendance Section
    path('attendance/<int:pk>/<date>/detail/', views.attendance_detail, name="attendance_detail"),
    # Home Work Section
    path('home-work/list/', views.home_work_list, name="home_work_list"),
    path('home-work/<int:pk>/detail/', views.home_work_detail, name="home_work_detail"),
    # Employment Form Section
    path('employment-form/list/', views.employment_form_list, name="employment_form_list"),
    path('employment-form/<int:pk>/detail/', views.employment_form_detail, name="employment_form_detail"),
    # News
    path('news/list/', views.news_list, name="news_list"),
)

main/models.py
from django.db import models


class SiteSetting(models.Model):
    COLOR_THEME = (
        ("green", "سبز"),
        ("orange", "نارنجی"),
        ("yellow", "زرد"),
    )
    MENU_THEME = (
        ('waterfall', 'منو آبشاری'),
        ("four_rooms", "منو چارخونه ای"),
    )

    # Fields
    school_name = models.CharField(
        max_length=20,
        verbose_name="نام مدرسه",
    )
    school_logo = models.ImageField(
        upload_to="main/school_logo/",
        verbose_name="لوگو مدرسه",
    )
    site_color = models.CharField(
        max_length=10,
        choices=COLOR_THEME,
        default="green",
        verbose_name="رنگ سایت",
    )
    site_menu_theme = models.CharField(
        max_length=15,
        choices=MENU_THEME,
        default="waterfall",
        verbose_name="تم منو سایت",
    )
    favicon = models.ImageField(
        upload_to="main/school_logo/",
        verbose_name="فاآیکون",
        null=True,
        blank=True,
    )

    # Metadata
    class Meta:
        verbose_name = 'تنظیمات سایت'
        verbose_name_plural = '01. تنظیمات سایت'

    # Methods
    def __str__(self):
        return self.school_name

main/views.py
import jdatetime
import feedparser
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import Http404
from django.shortcuts import (
    render,
    get_object_or_404, redirect,
)
from django.urls import reverse_lazy
from django.utils import timezone
from extensions.utils import change_month
from account.models import User
from main.decorators import (
    allow_user,
    allow_class_teacher,
    allow_att_teacher,
    allow_hw_student,
    allow_emp_form_student,
    parent_access,
    student_access,
)
from manager.filters import (
    ClassFilter,
    EMPFormFilter,
)
from manager.models import (
    NoticeBox,
    Major,
    Attendance,
    Classes,
    Books,
    HomeWork,
    EmploymentForm,
    Assign,
)


def index(request):
    if request.user.is_anonymous:
        return redirect(reverse_lazy("account:login"))
    if request.user.is_superuser or request.user.is_manager:
        return redirect(reverse_lazy('manager:manager_panel'))
    elif request.user.is_teacher:
        return redirect(reverse_lazy('teacher:teacher_panel'))
    elif request.user.is_parent:
        return redirect(reverse_lazy('parent:parent_panel'))
    elif request.user.is_student:
        return redirect(reverse_lazy('student:student_panel'))


@login_required()
def events(request):
    context = {
        "page_title": "رویداد ها",
        "notices": NoticeBox.objects.all()
    }
    return render(request, "main/events.html", context)


@login_required()
def notice_box(request):
    context = {
        "page_title": "اعلانات",
        "notices": NoticeBox.objects.all().order_by('-publish')
    }
    return render(request, "main/notice_box.html", context)


@parent_access()
@allow_user(['is_superuser', 'is_manager', 'is_parent', 'is_student'])
def student_detail(request, pk):
    def all_status_func():
        all_status = Assign.objects.filter(student=pk).aggregate(count=Count('id'))
        count_all = 0
        if all_status["count"] is not None:
            count_all = int(all_status["count"])
        return count_all

    def present_percent():
        present = Assign.objects.filter(student=pk, attendance_status='حاضر').aggregate(count=Count('id'))
        count_present = 0
        if present["count"] is not None:
            count_present = int(present["count"])
        result = round((count_present / all_status_func()) * 100, 0)
        return result

    def absent_percent():
        absent = Assign.objects.filter(student=pk, attendance_status='غایب').aggregate(count=Count('id'))
        count_present = 0
        if absent["count"] is not None:
            count_present = int(absent["count"])
        result = round((count_present / all_status_func()) * 100, 0)
        return result

    def plate_percent():
        plate = Assign.objects.filter(student=pk, attendance_status='حاضر (با تاخیر)').aggregate(
            count=Count('id'))
        count_present = 0
        if plate["count"] is not None:
            count_present = int(plate["count"])
        result = round((count_present / all_status_func()) * 100, 0)
        return result

    user = User.objects.filter(is_active=True, is_student=True)
    context = {
        'person': get_object_or_404(user, pk=pk),
        'page_title': 'جزئیات دانش آموز',
        'majors': Major.objects.all(),
        'present': present_percent(),
        'absent': absent_percent(),
        'plate': plate_percent(),
    }
    return render(request, "main/persons/person_detail.html", context)


@student_access()
@allow_user(['is_superuser', 'is_manager', 'is_parent'])
def parent_detail(request, pk):
    user = User.objects.filter(is_active=True, is_parent=True)
    context = {
        'person': get_object_or_404(user, pk=pk),
        'page_title': 'جزئیات والد یا قیم',
    }
    return render(request, "main/persons/person_detail.html", context)


@student_access()
@allow_user(['is_superuser', 'is_manager', 'is_teacher'])
def teacher_detail(request, pk):
    user = User.objects.filter(is_active=True, is_teacher=True)
    context = {
        'person': get_object_or_404(user, pk=pk),
        'page_title': 'جزئیات دبیر',
    }
    return render(request, "main/persons/person_detail.html", context)


@allow_user(['is_superuser', 'is_manager', 'is_teacher'])
def class_list(request):
    context = {
        'page_title': "لیست کلاس ها",
        'majors': Major.objects.all(),
    }
    if request.user.is_superuser or request.user.is_manager:
        context['filter'] = ClassFilter(request.GET, queryset=Classes.objects.all())
    elif request.user.is_teacher:
        context['filter'] = ClassFilter(request.GET, queryset=Classes.objects.filter(teacher__pk=request.user.pk))
    else:
        raise Http404()
    return render(request, "main/classes/class_list.html", context)


@allow_class_teacher()
@allow_user(['is_superuser', 'is_manager', 'is_teacher'])
def class_detail(request, pk):
    cls = get_object_or_404(Classes, pk=pk)
    context = {
        "class": cls,
        "page_title": "جزئیات کلاس",
        'atts': Classes.objects.filter(pk=pk, attendance_class__pk=pk),
        'jalali_date': change_month(str(jdatetime.date.fromgregorian(date=timezone.now()))),
        'books': Books.objects.filter(grade__pk=cls.grade.pk, major__pk=cls.major.pk),
    }
    return render(request, "main/classes/class_detail.html", context)


@allow_att_teacher()
@allow_user(['is_superuser', 'is_manager', 'is_teacher'])
def attendance_detail(request, pk, date):
    context = {
        "attendance": get_object_or_404(Attendance, pk=pk, date=date),
        "page_title": "جزئیات حضور و غیاب",
    }
    return render(request, "main/classes/class_detail.html", context)


@allow_user(['is_superuser', 'is_manager', 'is_teacher', 'is_student'])
def home_work_list(request):
    context = {
        'page_title': 'لیست تکالیف',
    }
    if request.user.is_superuser or request.user.is_manager:
        context['home_works'] = HomeWork.objects.all()
    elif request.user.is_student:
        context['home_works'] = HomeWork.objects.filter(attendance__attendance_class=request.user.student_class)
    elif request.user.is_teacher:
        context['home_works'] = HomeWork.objects.filter(attendance__attendance_class__teacher__pk=request.user.pk)
    return render(request, 'main/classes/class_list.html', context)


@allow_hw_student()
@allow_user(['is_superuser', 'is_manager', 'is_teacher', 'is_student'])
def home_work_detail(request, pk):
    context = {
        'page_title': 'جزئیات تکلیف',
        'home_work': get_object_or_404(HomeWork, pk=pk)
    }
    return render(request, 'main/classes/class_detail.html', context)


@allow_user(['is_superuser', 'is_manager', 'is_student'])
def employment_form_list(request):
    context = {
        "page_title": "لیست فرم های اشتغال به تحصیل",
    }
    if request.user.is_superuser or request.user.is_manager:
        context['filter'] = EMPFormFilter(request.GET, queryset=EmploymentForm.objects.all())
    elif request.user.is_student:
        context['filter'] = EMPFormFilter(request.GET,
                                          queryset=EmploymentForm.objects.filter(student__pk=request.user.pk))
    return render(request, 'main/classes/class_list.html', context)


@allow_emp_form_student()
@allow_user(['is_superuser', 'is_manager', 'is_student'])
def employment_form_detail(request, pk):
    context = {
        'page_title': 'جزئیات فرم',
        'employment_form': get_object_or_404(EmploymentForm, pk=pk)
    }
    if request.method == "POST":
        if request.is_ajax:
            input_value = {
                'status': request.POST.get('status'),
                'emp_form_id': request.POST.get('emp_form_id'),
            }
            print(input_value)
            EmploymentForm.objects.filter(id=input_value['emp_form_id']).update(status=input_value['status'])

    return render(request, 'main/classes/class_detail.html', context)


@login_required()
def news_list(request):
    feeds = feedparser.parse('https://www.mehrnews.com/rss/tp/68')
    context = {
        'feeds': feeds,
        'page_title': 'اخبار آموزش و پرورش'
    }
    return render(request, "main/news_list.html", context)

main/templates/main/classes/class_list.html
{% extends 'base.html' %}

{% block main %}
<div class="m-2">
    {% if request.resolver_match.url_name == "class_list" %}
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>لیست کلاس ها</h3>
    </div>
    <!-- Breadcubs Area End Here -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card dashboard-card-eleven">
                <div class="card-body user_list">
                    <div class="table-box-wrap">
                        <form class="search-form-box">
                            <div class="row gutters-8">
                                <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
                                    <span class="small mb-1">فیلتر بر اساس مقطع</span>
                                    <div class="d-block">
                                        {{ filter.form.grade }}
                                    </div>
                                </div>
                                {% if majors %}
                                <div class="col-lg-3 col-12 form-group">
                                    <span class="small mb-1">فیلتر بر اساس رشته</span>
                                    <div class="d-block">
                                        {{ filter.form.major }}
                                    </div>
                                </div>
                                {% endif %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <span class="small mb-1">جستجو بر اساس نام</span>
                                    </div>
                                    <div class="col-lg-5 col-6 form-group">
                                        {{ filter.form.name }}
                                    </div>
                                    <div class="col-lg-3 col-6 form-group">
                                        <button type="submit" class="btn search_btn">جستجو
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="table-responsive student-table-box">
                            <table class="table display data-table text-nowrap">
                                <thead>
                                <tr>
                                    <th>نام کلاس</th>
                                    <th>مقطع</th>
                                    <th>رشته</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for class in filter.qs %}
                                <tr class="filter">
                                    <td><a href="{% url 'main:class_detail' class.pk %}"><b>{{ class.name }}</b></a>
                                    </td>
                                    <td>{{ class.grade }}</td>
                                    <td>{{ class.major }}</td>
                                    <td>
                                        <div class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                               aria-expanded="false">
                                                <span class="flaticon-more-button-of-three-dots"></span>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item"
                                                   href="{% url 'main:class_detail' class.pk %}"><i
                                                        class="fas fa-cogs text-dark-pastel-green"></i>جزئیات</a>
                                                <a class="dropdown-item" href="{% url 'main:class_list' %}"><i
                                                        class="fas fa-redo-alt text-orange-peel"></i>تازه کردن</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td>
                                        <p class="text-danger font-weight-bold">نتیجه ای وجود ندارد</p>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% elif request.resolver_match.url_name == "home_work_list" %}
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>لیست تکالیف</h3>
    </div>
    <!-- Breadcubs Area End Here -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card dashboard-card-eleven">
                <div class="card-body user_list">
                    <div class="table-box-wrap">
                        <div class="table-responsive student-table-box">
                            <table class="table display data-table text-nowrap">
                                <thead>
                                <tr>
                                    <th>عنوان</th>
                                    <th>تاریخ</th>
                                    <th>درس</th>
                                    {% if request.user.is_superuser or request.user.is_manager %}
                                    <th>کلاس</th>
                                    {% endif %}
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for hw in home_works %}
                                <tr class="filter">
                                    <td><a href="{% url 'main:home_work_detail' hw.pk %}"><b>{{ hw.title }}</b></a>
                                    </td>
                                    <td>{{ hw.date }}</td>
                                    <td>{{ hw.attendance.book }}</td>
                                    {% if request.user.is_superuser or request.user.is_manager %}
                                    <td>{{ hw.attendance.attendance_class }}</td>
                                    {% endif %}
                                    <td>
                                        <div class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                               aria-expanded="false">
                                                <span class="flaticon-more-button-of-three-dots"></span>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item"
                                                   href="{% url 'main:home_work_detail' hw.pk %}"><i
                                                        class="fas fa-cogs text-dark-pastel-green"></i>جزئیات</a>
                                                <a class="dropdown-item" href=""><i
                                                        class="fas fa-redo-alt text-orange-peel"></i>تازه کردن</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td>
                                        <p class="text-danger font-weight-bold">نتیجه ای وجود ندارد</p>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% elif request.resolver_match.url_name == "employment_form_list" %}
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>لیست فرم های اشتغال به تحصیل</h3>
    </div>
    <!-- Breadcubs Area End Here -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card dashboard-card-eleven">
                <div class="card-body user_list">
                    <div class="table-box-wrap">
                        <form class="search-form-box">
                            <div class="row gutters-8">
                                <div class="row">
                                    <div class="col-md-12">
                                        <span class="small mb-1">فیلتر بر اساس وضعیت</span>
                                    </div>
                                    <div class="col-lg-5 col-6 form-group">
                                        {{ filter.form.status }}
                                    </div>
                                    <div class="col-lg-3 col-6 form-group">
                                        <button type="submit" class="btn search_btn">جستجو
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="table-responsive student-table-box">
                            <table class="table display data-table text-nowrap">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>نام دانش آموز</th>
                                    <th>اُرگان مورد نظر</th>
                                    <th>وضعیت</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for emp_form in filter.qs %}
                                <tr class="filter">
                                    <td>{{ emp_form.id }}</td>
                                    <td><a href="{% url 'main:employment_form_detail' emp_form.pk %}"><b>{{ emp_form.student }}</b></a>
                                    </td>
                                    <td>{{ emp_form.organ|truncatechars:10 }}</td>
                                    <td><div class="badge p-2 badge-{% if emp_form.status == 'بررسی شده' %}success{% elif emp_form.status == 'در انتظار بررسی'  %}warning{% elif emp_form.status == 'رد شده'  %}danger{% endif %}">{{ emp_form.status }}</div> </td>
                                    <td>
                                        <div class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                               aria-expanded="false">
                                                <span class="flaticon-more-button-of-three-dots"></span>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item"
                                                   href="{% url 'main:employment_form_detail' emp_form.pk %}"><i
                                                        class="fas fa-cogs text-dark-pastel-green"></i>جزئیات</a>
                                                <a class="dropdown-item" href="{% url 'main:employment_form_list' %}"><i
                                                        class="fas fa-redo-alt text-orange-peel"></i>تازه کردن</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td>
                                        <p class="text-danger font-weight-bold">نتیجه ای وجود ندارد</p>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}